name: Kubernetes Compatible

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-compatible:
    strategy:
      matrix:
        node-image:
          - kindest/node:v1.31.14@sha256:6f86cf509dbb42767b6e79debc3f2c32e4ee01386f0489b3b2be24b0a55aac2b
          - kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8
          - kindest/node:v1.33.7@sha256:d26ef333bdb2cbe9862a0f7c3803ecc7b4303d8cea8e814b481b09949d353040
          - kindest/node:v1.34.3@sha256:08497ee19eace7b4b5348db5c6a1591d7752b164530a36f855cb0f2bdcbadd48
          - kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Create kind cluster
        id: kind
        uses: helm/kind-action@v1
        with:
          node_image: ${{ matrix.node-image }}
          registry: true
          registry_name: my-registry
          registry_port: 5001
          registry_enable_delete: true

      - name: Verify kind installation
        run: |
          kubectl cluster-info

      - name: Build webhook
        id: build
        run: |
          IMAGE_TAG=$(openssl rand -hex 4)
          IMAGE_REPOSITORY=${{ steps.kind.outputs.LOCAL_REGISTRY }}/alidns-webhook
          IMAGE_NAME=$IMAGE_REPOSITORY IMAGE_TAG=$IMAGE_TAG make build
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_REPOSITORY=$IMAGE_REPOSITORY" >> $GITHUB_OUTPUT

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify helm installation
        run: |
          helm version

      - name: Install cert-manager
        run: |
          helm upgrade cert-manager cert-manager --install \
            --repo https://charts.jetstack.io \
            --set crds.enabled=true \
            --namespace cert-manager --create-namespace

      - name: Wait for cert-manager to be ready
        run: |
          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager
          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager-webhook
          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/cert-manager-cainjector

      - name: Install webhook
        run: |
          helm upgrade --install alidns-webhook alidns-webhook \
            --repo https://wjiec.github.io/alidns-webhook \
            --namespace cert-manager --create-namespace \
            --set groupName=acme.yourcompany.com \
            --set image.repository=${{ steps.build.outputs.IMAGE_REPOSITORY }} \
            --set image.tag=${{ steps.build.outputs.IMAGE_TAG }}

      - name: Wait for webhook to be ready
        run: |
          kubectl wait --namespace cert-manager --for=condition=available --timeout=300s deployment/alidns-webhook

      - name: Create ClusterIssuer
        id: cluster-issuer
        env:
          WEBHOOK_ACCESS_KEY_ID: ${{ secrets.WEBHOOK_ACCESS_KEY_ID }}
          WEBHOOK_ACCESS_KEY_SECRET: ${{ secrets.WEBHOOK_ACCESS_KEY_SECRET }}
        run: |
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: alidns-secret
            namespace: cert-manager
          stringData:
            access-key-id: "${WEBHOOK_ACCESS_KEY_ID}"
            access-key-secret: "${WEBHOOK_ACCESS_KEY_SECRET}"
          ---
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: example-acme
          spec:
            acme:
              server: https://acme-staging-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: example-acme
              solvers:
                - dns01:
                    webhook:
                      groupName: acme.yourcompany.com
                      solverName: alidns
                      config:
                        accessKeyIdRef:
                          name: alidns-secret
                          key: access-key-id
                        accessKeySecretRef:
                          name: alidns-secret
                          key: access-key-secret
          EOF

      - name: Wait for ClusterIssuer to be ready
        run: |
          kubectl wait --for=condition=ready --timeout=300s clusterissuer/example-acme

      - name: Create certificate
        env:
          WEBHOOK_DOMAIN_NAME: ${{ secrets.WEBHOOK_DOMAIN_NAME }}
        run: |
          RANDOM_SUB_DOMAIN=$(openssl rand -hex 6)
          kubectl apply -f - <<EOF
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: random-cert
          spec:
            secretName: random-tls
            commonName: "${RANDOM_SUB_DOMAIN}.${WEBHOOK_DOMAIN_NAME}"
            dnsNames:
              - "${RANDOM_SUB_DOMAIN}.${WEBHOOK_DOMAIN_NAME}"
            issuerRef:
              name: example-acme
              kind: ClusterIssuer
          EOF

      - name: Wait for certificate to be ready
        run: |
          kubectl wait --for=condition=ready --timeout=650s certificate/random-cert

  compatible-ok:
    if: always()
    needs: check-compatible
    runs-on: ubuntu-latest

    steps:
      - name: Report job result
        env:
          COMPATIBLE_BUILD_RESULT: ${{ needs.check-compatible.result }}
        run: |
          if [[ $COMPATIBLE_BUILD_RESULT == "success" ]]; then exit 0; fi
          exit 1
